id: QmRwtihRMHSC5kiAKYFWkYhA6sHY4BZ45gsZFECVFuMWEb
description: ""
tags: []
source: libraries/pixxame_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/getchannelurl
domains:
    - globalDomain
execution:
    timeout: 100s
    memory: 10MB
    call: getChannelUrl
