id: QmdPXgrR4kaL4XafgaCWkunAtV3dqUZDntFownF5oUqXqd
description: ""
tags: []
source: libraries/pixxame_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/chat
domains:
    - globalDomain
execution:
    timeout: 100s
    memory: 10MB
    call: getChat
